#!/bin/bash

## Files and cmd
FILE="$HOME/.cache/eww_launch.dashboard"
CFG="$HOME/.config/eww/dashboard"

 
run_eww() {
	eww daemon
	until pid=$(pidof eww)
	do
		sleep 1
	done
	eww --config "$CFG" open-many system music powerbuttons
}

if [[ ! -f "$FILE" ]]; then
	touch "$FILE"
 	run_eww
 else
 	eww --config "$CFG" close system music powerbuttons
 	rm "$FILE"
 fi
