#!/bin/bash

FILE="$HOME/.cache/eww_launch.calendar"
CFG="$HOME/.config/eww/calendar"

run_eww() {
	eww daemon
	until pid=$(pidof eww)
	do
		sleep 1
	done
	eww --config "$CFG" open calendar --screen 0
	}


if [[ ! -f "$FILE" ]]; then
	touch "$FILE"
	run_eww
else
	eww --config "$CFG" close calendar
	rm "$FILE"
fi
