#!/bin/bash

if [[ "$1" == "--lock" ]]; then
	swaylock
elif [[ "$1" == "--logout" ]]; then
	loginctl kill-session self
elif [[ "$1" == "--suspend" ]]; then
	suspend
elif [[ "$1" == "--reboot" ]]; then
	reboot
elif [[ "$1" == "--poweroff" ]]; then
	poweroff
fi
