#!/bin/bash

## Files and cmd
FILE="$HOME/.cache/eww_launch.calendar"
EWW="eww -c $HOME/.config/eww/calendar"

## Run eww daemon if not running already
if [[ ! `pidof eww` ]]; then
	${EWW} daemon
	sleep 1
fi

## Open widgets 
run_eww() {
	${EWW} open calendar --screen 0
        
}

## Launch or close widgets accordingly
if [[ ! -f "$FILE" ]]; then
	touch "$FILE"
	run_eww
else
	${EWW} close calendar
	rm "$FILE"
fi
